// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sale.Data;

namespace Sale.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Sale.Data.Model.BaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddedBy");

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 6, 28, 16, 56, 50, 953, DateTimeKind.Local).AddTicks(4676));

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 6, 28, 16, 56, 50, 954, DateTimeKind.Local).AddTicks(8589));

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseEntity");
                });

            modelBuilder.Entity("Sale.Data.Model.CartProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CartId");

                    b.Property<int>("OnCartAmount");

                    b.Property<long>("ProductId");

                    b.HasKey("Id");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("Sale.Data.Model.Cart", b =>
                {
                    b.HasBaseType("Sale.Data.Model.BaseEntity");

                    b.Property<long?>("SaleId");

                    b.Property<long>("UserId");

                    b.HasDiscriminator().HasValue("Cart");
                });

            modelBuilder.Entity("Sale.Data.Model.Category", b =>
                {
                    b.HasBaseType("Sale.Data.Model.BaseEntity");

                    b.Property<string>("Name");

                    b.HasDiscriminator().HasValue("Category");
                });

            modelBuilder.Entity("Sale.Data.Model.Product", b =>
                {
                    b.HasBaseType("Sale.Data.Model.BaseEntity");

                    b.Property<bool>("Active");

                    b.Property<long>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<decimal>("Price");

                    b.Property<int>("Stock");

                    b.Property<string>("Title");

                    b.HasIndex("CategoryId");

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("Sale.Data.Model.Sale", b =>
                {
                    b.HasBaseType("Sale.Data.Model.BaseEntity");

                    b.Property<int>("PaymentType");

                    b.Property<decimal>("TotalPrice");

                    b.Property<string>("UserFullname");

                    b.Property<long>("UserId")
                        .HasColumnName("Sale_UserId");

                    b.HasDiscriminator().HasValue("Sale");
                });

            modelBuilder.Entity("Sale.Data.Model.User", b =>
                {
                    b.HasBaseType("Sale.Data.Model.BaseEntity");

                    b.Property<string>("Fullname");

                    b.Property<bool>("IsAuthenticate");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<string>("Username");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Sale.Data.Model.Product", b =>
                {
                    b.HasOne("Sale.Data.Model.Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
